### ISSUE TITLE
Infografia

### ISSUE THREAD

**Issue by Rosa218** [SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-Rosa218#2]
![Ingenieria de](https://user-images.githubusercontent.com/72048522/187010395-fd7c8867-c279-4efd-af70-72da2744b418.jpg)

**Comment by Abraham890** [comment]
Calificacion:20 Puntos

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
